### PR TITLE
Gin middleware (nrgin) records errors

### PR DESCRIPTION
**Pull request by kevinmichaelchen**
## Details

Existing [nrgin middleware](https://github.com/newrelic/go-agent/blob/v3/integrations/nrgin/v1.1.3/v3/integrations/nrgin/nrgin.go#L141-L149) did not record errors. Taking inspiration from [otelgin](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/instrumentation/github.com/gin-gonic/gin/otelgin/v0.36.1/instrumentation/github.com/gin-gonic/gin/otelgin/gintrace.go#L80-L89), this PR adds in error recording.

## TODOs

- [ ] Need to create a unit test for the error case

### CODE REVIEW

**Comment by iamemilio** [comment]
Please add myself and nr-swilloughby as reviewers, and un-draft this when you are ready for us to review. Also, please change the pull request to be against our staging branch, develop.  Thanks for contributing!

**Comment by kevinmichaelchen** [comment]
@iamemilio @nr-swilloughby — thanks for reaching out! sorry this PR has lagged (been busy). the unit test failures caught me by surprise, so that's where i'm stuck. hope to take another look at it soon!

**Comment by iamemilio** [comment]
Some of our unit tests are just not working right now. As long as all of the go-agent-v3 tests are passing, then you're good. That seems to be the case here.

**Comment by Ak-x** [comment]
We are closing and re-opening to restart the test-suite.

**Comment by Ak-x** [comment]
@kevinmichaelchen are you able to sign the CLA here so that we can proceed?

**Pull request closed without merging**
