### PR TITLE
Update logrus import

### PR DESCRIPTION
**Pull request by alfred-landrum**
Related to https://github.com/sirupsen/logrus/issues/451 .

### CODE REVIEW

**Comment by jeffrand** [comment]
@willnewrelic mind taking a look at this PR?

**Comment by bflee890** [comment]
Is there any update on this?

**Comment by johnwu96822** [comment]
Can this be merged and released asap? The problem is kind of annoying!!

**Comment by mihaitodor** [comment]
@willnewrelic @nehaduggal Has this project been completely abandoned? This is a trivial change which allows people to use this library. Please have somebody merge it.

**Comment by robertnewrelic** [comment]
Thanks for the PR @alfred-landrum !  We've merged your change to our testing environment, which will makes its way into the next release.  We do not yet have an exact date for the release but it will be coming shortly, as we're actively working on it.

**Pull request closed without merging**
