### PR TITLE
Adds Aerospike in Datastore

### PR DESCRIPTION
**Pull request by vkartik97**
This PR proposes to add `Aerospike` for Datastore Segment NR Transaction

### CODE REVIEW

**Comment by pyohannes** [comment]
Hi @vkartik97!

We are investigating adding this datastore. Thanks for opening this!

**Comment by Miriam-R** [comment]
Would we want to add this to the Go Agent or the OTel Agent @jodeev

**Comment by RichVanderwal** [comment]
@jodeev would like to get this into the next release.

**Review by RichVanderwal — APPROVED** [review]
Thanks @vkartik97 , this looks good! I've switched this PR to be merged into `newrelic:develop` instead of `newrelic:master`. We're hoping to include this in the upcoming maintenance release for the Go Agent.

**Pull request merged**
