### PR TITLE
Fix typos in log_event.go

### PR DESCRIPTION
**Pull request by gqgs**

### CODE REVIEW

**Comment by iamemilio** [comment]
Thanks for the pull request :)

**Review by iamemilio — APPROVED** [review]

**Comment by iamemilio** [comment]
Sorry, could you rebase this against develop? We don't stage changes in master

**Comment by gqgs** [comment]
@iamemilio Rebased.

**Review by iamemilio — APPROVED** [review]
Awesome, thanks for contributing!

**Review by nr-swilloughby — APPROVED** [review]

**Pull request merged**
