### PR TITLE
Aws gomod

### LINKED ISSUE #510: update go.mod for v3/integrations/nrawssdk-v1
The nrawssdk-v1 module actually relies on v3.16.0 of the super module. Please update its go.mod file accordingly.

https://github.com/newrelic/go-agent/blob/a0f3666caec5305df9768dc177c553a1a8d75d3b/v3/integrations/nrawssdk-v1/go.mod#L11

### PR DESCRIPTION
**Pull request by sdbedi**
Update aws go.mod to 3.16.0
closes #510

### CODE REVIEW

**Review by nr-swilloughby — CHANGES_REQUESTED** [review]
Why does this PR, which corrects the `go.mod` for `nrawssdk-v1` also include the commit to change the `go.mod` for `nrgin` (which already has its own PR)? It should just have the changes for nrawssdk-v1.

**Review by nr-swilloughby — APPROVED** [review]
approving commit 5f34b416f3aa7cd83a486bfda26b8617c1ad2ba0

**Comment by nr-swilloughby** [comment]
submitted pr 527 to replace this pr, but limited to the actual needed change.

**Comment by sdbedi** [comment]
Sorry about that! Looks like I based the branch for this PR off one I had used previously.

**Comment by nr-swilloughby** [comment]
No problem, we fixed it. Thanks for the PR.

**Pull request closed without merging**
