### PR TITLE
Update nrgin go.mod to mitigate security issue in 3rd party dependency

### PR DESCRIPTION
**Pull request by sdbedi**
Update gin-gonic to version 1.7.7

### CODE REVIEW

**Comment by nr-swilloughby** [comment]
Changed the PR base branch. It is our policy to merge changes only to `develop`.

**Comment by nr-swilloughby** [comment]
This fixes [Issue 513](https://github.com/newrelic/go-agent/issues/513)

**Comment by iamemilio** [comment]
LGTM

**Comment by MadScienceZone** [comment]
This is already planned for the next release once that is ready to go out.

**Comment by nr-swilloughby** [comment]
This is already planned for the next release once that is ready to go out.

**Review by nr-swilloughby — APPROVED** [review]

**Pull request merged**
