### PR TITLE
Updates examples to retrieve transaction using FromContext

### PR DESCRIPTION
**Pull request by kevburnsjr**
`FromContext` is the newer method for accessing a transaction from within an http handler.

These examples use a mix of type casting and `FromContext`. This PR makes them consistent.

I propose that New Relic update all documentation and examples removing type casting in favor of  `FromContext` to help prevent customers from experiencing issues related to the old type cast method.

Details regarding the type of problem type casting creates and why `FromContext` is strictly superior can be found in the following github issue for a piece of HTTP middleware that is incompatible with many newrelic integrations due to the widespread use of type casting for transaction retrieval: https://github.com/kevburnsjr/microcache/issues/10

### CODE REVIEW

**Comment by willnewrelic** [comment]
Hi @kevburnsjr 

Thank you!  We agree:  `FromContext` is a better way to get the transaction.

This example code was written before Go 1.7.  It is very old!

We appreciate your contribution.  Expect to see this in the next release.

**Comment by willnewrelic** [comment]
Hi @kevburnsjr

We just released version 2.14.0 with this change!

Thanks again for giving us this PR!

**Comment by kevburnsjr** [comment]
Don't forget about the docs  
https://docs.newrelic.com/docs/agents/go-agent/instrumentation/instrument-go-transactions#http-handler-txns  
https://docs.newrelic.com/docs/agents/go-agent/instrumentation/instrument-go-segments#go-nesting-segments

**Comment by purple4reina** [comment]
@kevburnsjr Thanks for finding those, they have been updated.

**Pull request merged**
