### PR TITLE
Added integration for ms sql server with newrelic

### PR DESCRIPTION
**Pull request by ishahid91**
Added intergation for ms sql server

## Details
Added integration for ms sql server to show database transactions on new relic. I have used the similar approach which is used in other integrations. I have added the relevant unit test and example as well which I tested on my local with sql server.

### CODE REVIEW

**Review by disiqueira-talabat — APPROVED** [review]
LGFM 👍

**Comment by RichVanderwal** [comment]
Thanks, @ishahid91 , for this PR! We'll be looking at it and considering it for inclusion in the Go Agent. It looks quite straightforward, and we're hoping to test it against a real MS SQL server soon!

Note that development generally slows down at the end of the calendar year, so our team most likely won't be looking closely at it until a few weeks have passed.

**Comment by ishahid91** [comment]
Thanks @RichVanderwal for looking at the PR and considering it to include in Go Agent. I am looking forward to get it included in Go Agent ASAP as this will help us and many other teams to monitor MS SQL Server for many critical Go services.

**Comment by ishahid91** [comment]
Hi @RichVanderwal, Any update on the review ? Looking forward to get it merged so that we can integrate it into our production services.

**Comment by ishahid91** [comment]
@RichVanderwal gentle reminder.

**Comment by iamemilio** [comment]
@ishahid91 Hi, are you still interested in merging this? We will help you  :)

**Comment by ishahid91** [comment]
Yes @iamemilio Can you please help merge this PR.

**Comment by iamemilio** [comment]
Overall, it looks good. Could you remove the dependency on ms-sql in the v3/go.mod file and verify that the changes still work?

**Comment by iamemilio** [comment]
@ishahid91 I was able to run this. Once you clean up the go lint errors, this is ready to merge: https://github.com/newrelic/go-agent/runs/6757623643?check_suite_focus=true


Thanks for submitting this, and thank you for being patient with us while we continue to grow our team!

**Review by iamemilio — APPROVED** [review]
Looks good, thanks!

**Comment by ishahid91** [comment]
@iamemilio Thanks for approving the PR. When I can expect this PR to be merged ?

**Comment by iamemilio** [comment]
It will very likely be merged in time for the next release!

**Review by nr-swilloughby — APPROVED** [review]

**Pull request merged**
