### PR TITLE
do not include distributed trace headers in AWS SDK requests

### LINKED ISSUE #427: AWS retry requests fail with 403 SignatureDoesNotMatch when newrelic distributed tracing is enabled.
## Description

Every aws retry request fails with 403 SignatureDoesNotMatch when newrelic
distributed tracing is enabled.

## Steps to Reproduce

Here is a piece of code that reproduces the problem. In this example I inject
the request handler which forces first request attempt to always fail with
retry-able error (of course I don't do it in production, it's just to simulate
aws sdk request retries). Then the retried request fails with aws
SignatureDoesNotMatch error which indicates that newrelic agent has modified
retired request in such a why that it makes request's signature invalid.
How do I know it that the problem is caused by newrelic agent? If I remove the
line where I add newrelic txn to ctx then request is retried successfully.

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
	"github.com/aws/aws-sdk-go/service/s3/s3manager"
	"github.com/newrelic/go-agent/v3/integrations/nrawssdk-v1"
	"github.com/newrelic/go-agent/v3/newrelic"
)

func main() {
	s3bucket := "REDACTED"
	s3key := "REDACTED"
	nrLicenseKey := "REDACTED"
	nrAppName := "REDACTED"

	nrApp, err := newrelic.NewApplication(
		newrelic.ConfigAppName(nrAppName),
		newrelic.ConfigLicense(nrLicenseKey),

		func(config *newrelic.Config) {
			config.SpanEvents.Enabled = true
			config.DistributedTracer.Enabled = true
		},
	)
	if err != nil {
		log.Fatal(err)
	}

	if err := nrApp.WaitForConnection(5 * time.Second); nil != err {
		log.Fatal(err)
	}

	sess := session.Must(session.NewSessionWithOptions(session.Options{
		SharedConfigState: session.SharedConfigEnable,
	}))
	sess.Config.WithLogLevel(aws.LogDebugWithSigning | aws.LogDebugWithRequestErrors)

	nrawssdk.InstrumentHandlers(&sess.Handlers)

	// This forces the very first aws request to fail with retriable error.
	sess.Handlers.Send.SetBackNamed(request.NamedHandler{
		Name: "ForceFirstAttemptToFailWithRetriableError",
		Fn: func(r *request.Request) {
			if r.RetryCount == 0 {
				r.Error = &retryableError{}
			}
		},
	})

	txn := nrApp.StartTransaction("test_txn")
	defer txn.End()

	ctx := context.Background()

	// if you comment out the following line everything works fine: the
	// request is successfully retried by aws sdk
	ctx = newrelic.NewContext(ctx, txn)

	_, err = s3manager.NewDownloaderWithClient(s3.New(sess)).
		DownloadWithContext(ctx, aws.NewWriteAtBuffer([]byte{}), &s3.GetObjectInput{
			Bucket: aws.String(s3bucket),
			Key:    aws.String(s3key),
		})
	if err != nil {
		log.Fatal(err)
	}
}

type retryableError struct{}

func (e *retryableError) Error() string   { return "retry-able error" }
func (e *retryableError) Temporary() bool { return true }
```

## Expected Behavior

Newrelic agent does not make aws signature invalid when the aws request is
retried.

## Your Environment

Software versions from go.mod:

```
github.com/aws/aws-sdk-go v1.37.18
github.com/newrelic/go-agent/v3 v3.13.0
github.com/newrelic/go-agent/v3/integrations/nrawssdk-v1 v1.0.1
```

## Additional context

When I run the code example I posted above I see that the first request doesn't
have `newrelic,traceparent,tracestate` http headers. However retries have this
headers. My wild guess is that this additional headers that appear only in
retries make the aws signature invalid. You can see the logs [here](https://gist.github.com/andriiberezhynskyi/b3f472dddcfa348a768633d9ed534cf7).

This might seem like an edge case as this happens only if aws request is retried
but it turned out that aws s3 api returns retriable 500 http status code often
enough to make this problem quite annoying.

### PR DESCRIPTION
**Pull request by rittneje**
Fixes #427 and #432. Sending the distributed trace headers to AWS is rather pointless, and can cause the request signature to be corrupted on retries. Also, previously the AWS request id and response status code were not being properly captured.

Note: Due to breaking changes in the v3/internal package, the new release of nrawssdk-v1 will depend on the new release of v3. Not sure how this is normally dealt with.

### CODE REVIEW

**Comment by rittneje** [comment]
ping @nr-swilloughby

**Comment by nr-swilloughby** [comment]
@rittneje thank you for reporting this issue and for suggesting a pull request to address it. We'll review the issue and work to resolve it ASAP.

**Comment by RichVanderwal** [comment]
@rittneje Thanks for working on this solution that simply side-steps the whole issue. We still need to do some testing on this, and would welcome others' feedback on this solution!

**Comment by RichVanderwal** [comment]
Tested with sample code, merging with develop.

**Review by RichVanderwal — APPROVED** [review]

**Pull request merged**
