### PR TITLE
Add support for WrapHTTPHandler

### PR DESCRIPTION
**Pull request by polds**
References #9.

Adds support for using `http.ListenAndServe`. Makes an opinionated assumption that the transaction name is the same as the requested URL Path.

A sad side effect is that the injected ResponseWriter can't be asserted (At least in Martini)

EDIT: I'm pretty sure this is due to Martini's dependency injection. 

Please see my test below:

```
package main

import (
    "errors"
    "log"
    "net/http"
    "time"

    "github.com/go-martini/martini"
    "github.com/newrelic/go-agent"
)

func main() {
    config := newrelic.NewConfig("Test-Martini", "KEY_NAME")
    app, err := newrelic.NewApplication(config)
    if err != nil {
        log.Fatal(err.Error())
    }

    m := martini.Classic()
    m.Get("/build", func() string {
        return "12345"
    })
    m.Get("/hello/:p", func(params martini.Params) string {
        return "Hello " + params["p"]
    })
    m.Get("/slow", func() string {
        time.Sleep(3 * time.Second)
        return "OK"
    })
    m.Get("/custom", func(w http.ResponseWriter, req *http.Request) string {
        if txn, ok := w.(newrelic.Transaction); ok {
            txn.AddAttribute("CustomKey", "CustomValue")
            txn.SetName("CustomName")
            txn.NoticeError(errors.New("CustomError"))
        } else {
            // This triggers, but shouldn't.
            log.Println("Couldn't assert the type.")
        }

        return "custom things have happened"
    })

    http.ListenAndServe(":3000", newrelic.WrapHTTPHandler(app, m))
}
```

### CODE REVIEW

**Comment by polds** [comment]
Hmm.. That indeed is a good catch. I wonder at the overhead of adding NewRelic as a middleware. Most http routers don't (easily) allow you to set the invocation order. So I feel that if you put NewRelic into a middleware you won't likely get the _whole_ picture of a request.

Someone correct me if I'm wrong.

**Comment by sergeylanzman** [comment]
Yes it's true.
But if only a 0.001% difference in response time. That most of the time goes on http hendler

**Comment by sergeylanzman** [comment]
Yes it's true.
But if only a 0.001% difference in response time. That most of the time goes on http hendler

**Comment by willnewrelic** [comment]
Hi @polds 

Unfortunately, as @sergeylanzman mentioned, using the path as the transaction name can be dangerous in situations where path fields contain dynamic values.  As a result, we are going to decline this PR.  We appreciate your desire to contribute back nonetheless!

Our strategy is going to be to add framework specific packages to make instrumentation easier.

Sorry for the long delayed response.

**Pull request closed without merging**
