### PR TITLE
add zerolog support for agent logs

### PR DESCRIPTION
**Pull request by jamesgoodhouse**
## Links

https://github.com/rs/zerolog

## Details

This adds a Zerolog integration for use with the agent's log system.

### CODE REVIEW

**Comment by iamemilio** [comment]
@jamesgoodhouse Please sign the CLA

**Comment by darshan-craft** [comment]
What can be done to move this forward if the CLA is not signed further? We are hoping to use the zerolog integration in our apps as well

**Review by iamemilio — APPROVED** [review]

**Comment by iamemilio** [comment]
Thank you @jamesgoodhouse

**Comment by iamemilio** [comment]
Unfortunately, we can not use this code as writtten until the CLA is coppied, since we do not have the rights to it.

**Comment by iamemilio** [comment]
@jamesgoodhouse One more ping 🙏 . I'll resolve your merge conflicts, just sign the CLA?

**Comment by jamesgoodhouse** [comment]
@iamemilio signed!

**Review by iamemilio — APPROVED** [review]

**Pull request merged**
