### PR TITLE
Logrus Logs in Context Support

### PR DESCRIPTION
**Pull request by iamemilio**
What this change adds

Logs in Context:
- log decorating package usable by all packages

Logrus:
- automatic log forwarding
- log metrics
- v2 log decorating

### CODE REVIEW

**Review by nr-swilloughby — DISMISSED** [review]

**Review by mirackara — APPROVED** [review]
Looks good!

**Comment by iamemilio** [comment]
Finally verified this with the help of @bizob2828, thanks again. This is ready to merge

**Comment by bizob2828** [comment]
Posting a screenshot of logs for posterity

screenshot 2022-07-22 at 11 14 13 AM

**Review by nr-swilloughby — DISMISSED** [review]

**Review by nr-swilloughby — APPROVED** [review]

**Comment by ivan-santos-eq** [comment]
Howdy! When is this feature going to be tagged/released?

**Comment by nr-swilloughby** [comment]
It's in process for release next week.

**Pull request merged**
