### PR TITLE
Echo v4 integration

### PR DESCRIPTION
**Pull request by alexmatsak**

### CODE REVIEW

**Comment by alexmatsak** [comment]
@willnewrelic is it possible to accept this PR ?

**Comment by willnewrelic** [comment]
Hi @alexmatsak

Thanks for the contribution!

Were changes required to support v4?  Do you know if it is possible to support "github.com/labstack/echo/v4" and previous "github.com/labstack/echo" versions without duplicating the code?

We've added this to issue our roadmap, and we will close this PR when we get it released.

**Comment by alexmatsak** [comment]
Hi @willnewrelic 

I tried to run echo v4 with current go-agent integration but got incompatible context error, so yes, this changes are required.

About code duplication i did so to avoid breaking changes and release minor version.
I think it may sense not waste time for this because everybody migrate to go modules and in future major release (with go mod support) you can drop it.

**Comment by brunoyb** [comment]
Hi!

Any updates on this? Now that Go 1.13 is out, adoption of Go Modules should increase.

Thanks!

**Comment by alexmatsak** [comment]
Hi @willnewrelic !
Any updates?

**Comment by willnewrelic** [comment]
Hi @alexmatsak !

Thanks for the poke!  We are planning on thinking about how we are going to version our integrations against different framework versions soon.  In addition, we definitely plan on using Go modules soon.  This change, and many others, are planned for a big major release:

https://github.com/newrelic/go-agent/issues/106

We apologize for letting this go unattended for this long!

**Comment by willnewrelic** [comment]
Hi @alexmatsak 

We are beta-ing version 3 of the Go agent:
https://github.com/newrelic/go-agent/tree/master/v3
https://godoc.org/github.com/newrelic/go-agent/v3/newrelic

In this V3 version, we have support for Echo v3 and Echo v4:
https://godoc.org/github.com/newrelic/go-agent/v3/integrations/nrecho-v3
https://godoc.org/github.com/newrelic/go-agent/v3/integrations/nrecho-v4

Sorry for the long delay.  We hope this pleases you!

**Pull request closed without merging**
