### PR TITLE
nrawssdk-v2: fix usage examples of nrawssdk.AppendMiddlewares

### PR DESCRIPTION
**Pull request by Meroje**
## Details

When testing the nrawssdk-v2 integration along with nrlambda I found out that the provided method of injecting the middleware to APIOptions does not work (no trace is seen for any aws call), what worked was to use the optFns param.

In this PR I'm only changing the documentation and example to reflect what has been working, but maybe you'd want to expand on it to add an exported function that can be used as an optFn ?

Also I could not find how to make the test fail as I'm not familiar enough with the internals.

### CODE REVIEW

**Comment by iamemilio** [comment]
@Meroje Hi, I'm taking a look at this and was wondering what this really changes other than when `nrawssdk.AppendMiddlewares(&awsConfig.APIOptions, nil)` is invoked.

**Comment by Meroje** [comment]
I found that the previous method had no effect and I would never get any telemetry from aws sdk.

**Comment by iamemilio** [comment]
Oh ok, that's a good reason haha. Ok, I'll verify this and see if we can land it in an upcoming release.

**Review by nr-swilloughby — APPROVED** [review]
These changes are approved and we're reviewing what potential changes to the integration may be needed to better support AWS as highlighted by this PR.

**Pull request merged**
