### PR TITLE
NewRelic - Gin integration - Get status code from a context copy

### PR DESCRIPTION
**Pull request by nacholupi**
Gin-gonic integration

Write the current status code when "flushHeader()" method is called

This PR is an alternative of this propose:
https://github.com/gin-gonic/gin/pull/1606

### CODE REVIEW

**Comment by nacholupi** [comment]
Hi @willnewrelic! could you take a look at it? Thanks

**Comment by willnewrelic** [comment]
Hi @nacholupi 

Thanks for this PR!  It is unfortunate that the our small Gin PR fix has not been accepted.  If that fix is not merged sometime soon, we will proceed with your alternative.  We appreciate your contribution.

**Comment by nacholupi** [comment]
Hi @willnewrelic. Your PR was merged! 
we can close this one, right?

**Comment by purple4reina** [comment]
@nacholupi Indeed @willnewrelic's PR was merged! We are all overjoyed. Thanks for staying up to date on this. I think it's finally safe to close this Pull Request! 🎉 🙌

**Pull request closed without merging**
