### PR TITLE
Add query to ParameterizedQuery

### PR DESCRIPTION
**Pull request by artefactop**
This PR fix the following issue and we are using it for a while with the desired behaviour

## Links

https://github.com/newrelic/go-agent/issues/436

## Details

We don't get much information about the queries because they are being grouped like 'select' on 'table' using 'Postgres'.

### CODE REVIEW

**Review by iamemilio — APPROVED** [review]

**Review by iamemilio — CHANGES_REQUESTED** [review]
Would it be possible to put a gate here that lets you disable this feature by default like this pull request? https://github.com/newrelic/go-agent/pull/637/files

**Comment by iamemilio** [comment]
We will happily merge these changes, but we want a way for them to be configured to be disabled by default first. Some customers will not appreciate data they were not expecting suddenly getting collected.

**Comment by bhaskar-simpl** [comment]
How about documenting that in the changelog?

**Comment by bhaskar-simpl** [comment]
One way I see is to create a separate version for nrpq that supports this. 
Can you quickly align on the solution rather than keeping this blocked forever?

**Comment by 99-deadshot** [comment]
@iamemilio please check #677 on priority

**Comment by iamemilio** [comment]
addressed in #745

**Pull request closed without merging**
