### PR TITLE
windows build

### PR DESCRIPTION
**Pull request by lvxv**

### CODE REVIEW

**Comment by ianomad** [comment]
Error on building for linux: timevalToDuration has been declared twice. Probably you should rename sampler.go into sampler_windows.go or separate out changes so that it doesn conflict with linux build.

**Comment by ianomad** [comment]
Made a fix for that #10

**Comment by victorNewRelic** [comment]
Hi @lvxv,
Thanks for submitting this PR. We're planning support for additional operating systems, including Windows, once we finish other critical features that are important for many customers.

When we're ready to work on support for Windows, we'll review the solution you've proposed in this PR. Until then, we'll label this PR to reflect that it's under consideration.

Best regards,
Victor Soares

**Comment by willnewrelic** [comment]
Hi

Version 1.5.0 was just released with Windows support!  Thanks for your interest and help @lvxv

**Pull request closed without merging**
