### PR TITLE
chore: add logs-in-context example with logrus

### PR DESCRIPTION
**Pull request by Julien4218**
## Details

This is a variation of the existing example for http-server, adding the specific steps to enable logs-in-context with distributed tracing.

image

### CODE REVIEW

**Comment by iamemilio** [comment]
rather than contribute this to v3/examples I think this would be a better fit for v3/integrations/logcontext-v2/nrlogrus/examples. Would you mind moving the file there? Thanks for contributing though, we are always happy to have more examples.

**Comment by Julien4218** [comment]
> rather than contribute this to v3/examples I think this would be a better fit for v3/integrations/logcontext-v2/nrlogrus/examples. Would you mind moving the file there? Thanks for contributing though, we are always happy to have more examples.

Sounds good, done.

**Review by iamemilio — APPROVED** [review]

**Comment by iamemilio** [comment]
Once you sign the CLA we can merge this.

**Comment by Julien4218** [comment]
> Once you sign the CLA we can merge this.

Done, thank you.

**Pull request merged**
