### PR TITLE
WIP: NR Gin Integration support retrieving transaction from context

### PR DESCRIPTION
**Pull request by bernardoVale**
## Details

We needed a way to instrument middlewares that are part of the request chain but before Gin Router.  We could, of course, start and end the transaction before the router, but then we would be measuring the time incorrectly for all endpoints since there was some computation outside the endpoint transaction.

The use case is easy to understand, we have a middleware for path rewrite, this kind of feature needs to be executed before the router. Gin doesn't provide any primitives for "pre routing" middlewares, so if you need that, you have to create a regular http.Handler and attach it before the router.  Like this:

```go
type testParentMiddleware struct {
	app *newrelic.Application
	key string
	next http.Handler
}

func (t *testParentMiddleware) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	txn := t.app.StartTransaction("parent")
	sgm := txn.StartSegment("parent-segment")
	txn.SetWebRequestHTTP(r)
	// imagine some computation here
	r = r.WithContext(context.WithValue(r.Context(), t.key, txn))
	sgm.End()
	t.next.ServeHTTP(rw, r)
}

func main() {
  app := NewNewrelicApp()
  key := "newrelic"
  router := gin.Default()
  router.Use(nrgin.MiddlewareWithTransaction(app, key))
  handler := testParentMiddleware{
		app:  app.Application,
		key: key,
		next: router,
   }
  // attach handler to an http.Server{}
}
```

This is the best solution we found so far, start the transaction in the first middleware and adapt `nrgin` to conditionally retrieve the transaction from `http.Request` context.

Before writing tests and polishing docs, I want to receive some initial feedback so I can avoid wasting my time.

### CODE REVIEW

**Comment by rvanderwal-newrelic** [comment]
Thanks for the PR, @bernardoVale ! I'll be looking at this so we can address any concerns we have with this approach.

**Comment by bernardoVale** [comment]
@rvanderwal-newrelic any updates? We're running 100% of production traffic with this code by the way :)

**Comment by matheus-meneses** [comment]
Hi Guys, any update about this feature?

**Comment by jodeev** [comment]
Thank you for your patience. I've heard interest in this from others as well. 

We'll have another look at this, we haven't forgotten it.

**Comment by matheus-meneses** [comment]
Hello Guys, any updates about this PR?

**Comment by nr-swilloughby** [comment]
Apologies for the delay on this. We're looking at it and should have an update for you soon.

**Comment by Ak-x** [comment]
@matheus-meneses if this is still of interest are you able to resolve the merge conflict?

**Pull request closed without merging**
